# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

current_time <- function() {
    invisible(.Call(`_dcpp_current_time`))
}

dcpp_attribs <- function() {
    .Call(`_dcpp_dcpp_attribs`)
}

dcpp_callWithOne <- function(f) {
    .Call(`_dcpp_dcpp_callWithOne`, f)
}

dcpp_fib <- function(n) {
    .Call(`_dcpp_dcpp_fib`, n)
}

dcpp_fred <- function(x, y) {
    .Call(`_dcpp_dcpp_fred`, x, y)
}

dcpp_is_na_2 <- function(x) {
    .Call(`_dcpp_dcpp_is_na_2`, x)
}

dcpp_is_na <- function(x) {
    .Call(`_dcpp_dcpp_is_na`, x)
}

dcpp_lapply <- function(input, f) {
    .Call(`_dcpp_dcpp_lapply`, input, f)
}

dcpp_LinearRegression <- function(x, y) {
    .Call(`_dcpp_dcpp_LinearRegression`, x, y)
}

dcpp_max <- function(x) {
    .Call(`_dcpp_dcpp_max`, x)
}

dcpp_mean <- function(x) {
    .Call(`_dcpp_dcpp_mean`, x)
}

dcpp_missing_sampler <- function() {
    .Call(`_dcpp_dcpp_missing_sampler`)
}

dcpp_mpe <- function(mod) {
    .Call(`_dcpp_dcpp_mpe`, mod)
}

dcpp_pdist_two <- function(x, ys) {
    .Call(`_dcpp_dcpp_pdist_two`, x, ys)
}

dcpp_pdist <- function(x, ys) {
    .Call(`_dcpp_dcpp_pdist`, x, ys)
}

dcpp_rowSums <- function(x) {
    .Call(`_dcpp_dcpp_rowSums`, x)
}

dcpp_scalar_missings <- function() {
    .Call(`_dcpp_dcpp_scalar_missings`)
}

dcpp_slope <- function(x, y) {
    .Call(`_dcpp_dcpp_slope`, x, y)
}

dcpp_sum <- function(r_vector) {
    .Call(`_dcpp_dcpp_sum`, r_vector)
}

